### ISSUE TITLE
Need titles for c1-6.md

### ISSUE THREAD

**Issue by loraxle** [loraxle/History-of-Computer-Communications#7]
Titles not showing for special company pages (c1-6) (Codex, Micom, 3Com, etc.)

**Comment by pydevcs** [comment]
This was because those pages were saying they were on chapter 17, and there was no chapter 17 in _chapters. So if you need that to be named something other than "Appendix C", you will need to update the chapter title here https://github.com/loraxle/History-of-Computer-Communications/blob/master/_chapters/17.md

**Comment by loraxle** [comment]
Thanks!
